apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-deployment
  labels:
    app: movie-service
spec:
  replicas: 1  # Nombre de répliques souhaitées
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: votre-utilisateur/movie-service:latest  # Remplacez par l'image Docker construite pour votre service movie_service
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: "postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev"
        - name: CAST_SERVICE_HOST_URL
          value: "http://cast_service:8000/api/v1/casts/"
