# templates/postgres/cast_db/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.cast_db.image.repository }}:{{ .Values.postgres.cast_db.image.tag }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.cast_db.credentials.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.cast_db.credentials.password }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.cast_db.database.name }}
