apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app  # Nom du service, prendra le nom de la release
  labels:
    app: {{ .Release.Name }}-app
    environment: dev
spec:
  selector:
  type: {{ .Values.service.type }}
    app: {{ .Release.Name }}-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  # Port exposé par le service !
      #targetPort: {{ .Values.service.port }}  # Port cible sur le pod
