apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}  # Nom du service, prendra le nom de la release
  labels:
    app: cast-app
    environment: dev
spec:
  selector:
    app: cast-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  # Port exposé par le service !
      #targetPort: {{ .Values.service.port }}  # Port cible sur le pod
