apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: {{ .Values.nginx.service.NodePort }}
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx